# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Minkyun Seo
title: Undergraduate Researcher
email: funboy0804@snu.ac.kr
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: minkyunseo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: __ming.s
linkedin_username: minkyun-seo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/myprofile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Minkyun and I am a passionate and self-motivated undergraduate student dedicated to achieving excellence in every project I undertake. I am eager to identify challenges inherent in the world and establish a value chain that not only tackles these issues but also fosters positive contributions to the broader community.
  <br> <br>
  <img src="https://img.shields.io/badge/Interests-Computer Vision(3D), Deep Learning-ffa500" height="22" />

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Undergaduate Research Intern
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Seoul National University
        caption: Jun 2023 - Present
        description: | # this will include new lines to allow paragraphs
          <div style="text-align: right; margin-top: -90px;" class="hidden-xs hidden-sm">
            <img src="https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Seoul_national_university_emblem.svg/1024px-Seoul_national_university_emblem.svg.png" alt="SNU logo" height="85"/> 
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Seoul_national_university_logotype.svg/1920px-Seoul_national_university_logotype.svg.png" alt="SNU logo" height="60"/>
          </div>
          Visual & Geometric Intelligence Laboratory (Prof. Jaesik Park) at SNU<br>
          • Dec 2023 - Present<br>
          • Working on 3D semantic segmentation
          <br>
          <br>
          AIoT Laboratory (Prof. Hyung-Sin Kim) at SNU<br>
          • Jun 2023 - Sep 2023<br>
          • Worked on Adaptive vision sensing: Real-time camera parameter control to enhance model performance

      - layout: top
        title: Presidental Security Service
        sub_title: South Korea
        caption: Jul 2021 - Jan 2023
        description: | # this will include new lines to allow paragraphs
          <div style="text-align: right; margin-top: -90px;" class="hidden-xs hidden-sm">
            <img src="https://i.namu.wiki/i/zxBIdOcRi9_7tHU47hoe48g4mKT2JPZC9wW0oqyt83pxx-bAeq7s8klTxOVxI99CJnCwYixZiVNX7CKcx5q1jA.svg" alt="PSS logo" height="85"/> 
          </div>
          Military Service: Korean Army, Honorable Discharged

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Seoul National University
        caption: 2019 - Present <br> 
          https://en.snu.ac.kr/
        sub_title: >
          B.S. in Architecture Engineering <br>
          B.S. in Computer Science and Engineering 
        description: | # this will include new lines to allow paragraphs
          <div style="text-align: right; margin-top: -130px;" class="hidden-xs hidden-sm">
            <img src="https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Seoul_national_university_emblem.svg/1024px-Seoul_national_university_emblem.svg.png" alt="SNU logo" height="85"/> 
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Seoul_national_university_logotype.svg/1920px-Seoul_national_university_logotype.svg.png" alt="SNU logo" height="60"/>
          </div>

      - layout: top
        title: Sejong Science High School
        caption: 2016 - 2019 <br>
          https://sjsh.sen.hs.kr/
        description: |
          <div style="text-align: right; margin-top: -110px;" class="hidden-xs hidden-sm">
            <img src="images/sjsh_logo.png" alt="SJSH logo" height="85"/> 
          </div>

  - title: Honors & awards # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: 1st place at SNU Creative Design Fair
        caption: 2023
        sub_title: Issued by Seoul National University
        description: | # this will include new lines to allow paragraphs
          SNU Creative Design Fair is an annual competition where engineering enthusiasts showcase <br>
          • Developed PlayEye, a toy for preventing pediatric myopia. I was responsible for the software, handling computer vision, and embedded systems. <br>
          • Visiting MWC 2024 (Barcelona)
      - layout: top
        title: National Excellence Scholarship (Full-ride)
        caption: 2021 - 2024
        sub_title: Issued by South Korea Government
      - layout: top
        title: Academic Excellence Scholarship (Full-ride)
        caption: 2019 - 2021
        sub_title: Issued by Seoul National University
        description: | # this will include new lines to allow paragraphs
          Initially received partial funding, full-ride since 2020.


  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
