# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Minkyun Seo
title: Undergraduate Researcher
email: funboy0804@snu.ac.kr
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: minkyunseo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: __ming.s
linkedin_username: minkyun-seo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/myprofile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Minkyun and I am a passionate and self-motivated undergraduate student dedicated to achieving excellence in every project I undertake. I am eager to identify challenges inherent in the world and establish a value chain that not only tackles these issues but also fosters positive contributions to the broader community.
  
  Currently I am interested in: <mark>Computer Vision (3D)</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Undergaduate Research Intern
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Seoul National University
        caption: Jun 2023 - Present
        description: | # this will include new lines to allow paragraphs
          Visual & Geometric Intelligence Laboratory (Prof. Jaesik Park) at SNU\\
          • Dec 2023 - Present\\
          • Working on 3D semantic segmentation
          <br>
          <br>
          AIoT Laboratory (Prof. Hyung-Sin Kim) at SNU\\
          • Jun 2023 - Sep 2023\\
          • Worked on Adaptive vision sensing: Real-time camera parameter control to enhance model performance

      - layout: left
        title: Presidental Security Service
        sub_title: South Korea
        caption: Jul 2021 - Jan 2023
        description: | # this will include new lines to allow paragraphs
          Military Service: Korean Army, Honorable Discharged

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seoul National University
        caption: 2019 - Present
        sub_title: >
          B.S. in Architecture Engineering <br>
          B.S. in Computer Science and Engineering
        description: | # this will include new lines to allow paragraphs
          TBD
  - title: Honors & awards # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Excellence Scholarship
        caption: 2021 - 2024
        sub_title: Issued by South Korea Government
        description: | # this will include new lines to allow paragraphs
          This scholarship supports undergraduates with strong academic performance in science and engineering, with the purpose of developing future leaders in those fields.      
      - layout: left
        title: Academic Excellence Scholarship
        caption: 2019 - 2021
        sub_title: Issued by Seoul National University
        description: | # this will include new lines to allow paragraphs
          Initially received partial funding. Demonstrated consistent dedication to academic achievements, which resulted in the scholarship being upgraded to a full-ride at 2020.

  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
